site_name: Sherwin-Williams
site_url: https://www.mkdocs.org/
site_description: Project documentation with Markdown.
site_author: Architecture Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: blob/master/docs/

theme:
  name: mkdocs
  color_mode: deep purple
  palette:
    primary: deep purple
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: 'G-274394082'}
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - Home: index.md
  - Architecture: getting-started.md
  - Standards: user-guide/
  - Micro Services: user-guide/
  - Design Pattern : dev-guide/
  - Team:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md

extra_css:
  - css/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables


hooks:
  - docs/hooks.py

plugins:
  - search
  - literate-nav:
      nav_file: README.md
      implicit_index: true


watch:
  - mkdocs
